<MyFloatLayout>
    id:layout
    Image:
        source:'D:\Game\Pictures\Tree.png'
        allow_stretch: True
        keep_ratio: False
    Button:
        id:button
        text:'Play'
        size_hint:0.3,0.1
        x: root.center_x-self.width/2
        y: root.center_y-self.height/2
        on_press:
            print(self.width,self.height)
            print(root.width,root.height)
            app.stop_sound()